return {
    furniture = {
        Couches = {
            { object = "miss_rub_couch_01", label = "Old Couch" },
            { object = "prop_fib_3b_bench", label = "Three-seater Couch" },
            { object = "prop_ld_farm_chair01", label = "Old Chair" },
            { object = "prop_ld_farm_couch01", label = "Old Three-seater Couch" },
            { object = "prop_ld_farm_couch02", label = "Old Striped Couch" },
            { object = "v_res_d_armchair", label = "Old Yellow Armchair" },
            { object = "v_res_fh_sofa", label = "Corner Sofa" },
            { object = "v_res_mp_sofa", label = "Corner Sofa 2" },
            { object = "v_res_d_sofa", label = "Couch 1" },
            { object = "v_res_j_sofa", label = "Couch 2" },
            { object = "v_res_mp_stripchair", label = "Couch 3" },
            { object = "v_res_m_h_sofa_sml", label = "Couch 4" },
            { object = "v_res_r_sofa", label = "Couch 5" },
            { object = "v_res_tre_sofa", label = "Couch 6" },
            { object = "v_res_tre_sofa_mess_a", label = "Couch 7" },
            { object = "v_res_tre_sofa_mess_b", label = "Couch 8" },
            { object = "v_res_tre_sofa_mess_c", label = "Couch 9" },
            { object = "v_res_tt_sofa", label = "Couch 10" },
            { object = "prop_rub_couch02", label = "Couch 11" },
            { object = "v_ilev_m_sofa", label = "White Couch" },
            { object = "v_med_p_sofa", label = "Leather Brown Couch" },
            { object = "v_club_officesofa", label = "Pauper Couch" },
            { object = "bkr_prop_clubhouse_sofa_01a", label = "Black Couch" },
            { object = "apa_mp_h_stn_sofacorn_01", label = "Corner Sofa 3" },
            { object = "prop_couch_lg_02", label = "Wood Couch" },
            { object = "apa_mp_h_stn_sofacorn_10", label = "Corner Sofa 4" },
            { object = "apa_mp_h_yacht_sofa_02", label = "Brown Couch" },
            { object = "apa_mp_h_yacht_sofa_01", label = "White Long Couch" },
            { object = "prop_couch_01", label = "Sofa Cushions" },
            { object = "prop_couch_03", label = "Sofa Yellow" },
            { object = "prop_couch_04", label = "Leather Sofa Cushions" },
            { object = "prop_couch_lg_05", label = "Corduroy Sofa" },
            { object = "prop_couch_lg_06", label = "Leather Brown Sofa 2" },
            { object = "prop_couch_lg_07", label = "Sofa Cushions 2" },
            { object = "prop_couch_lg_08", label = "Leather Brown Sofa 3" },
            { object = "prop_couch_sm1_07", label = "Leather Corner Sofa" },
            { object = "prop_couch_sm2_07", label = "Leather Straight Sofa" },
            { object = "prop_couch_sm_06", label = "Small Leather Sofa" },        
        },
        
        Chairs = {
            { object = "v_res_d_highchair", label = "High chair" },
            { object = "apa_mp_h_stn_chairstrip_03", label = "Sitchair 4" },
            { object = "v_res_fa_chair01", label = "Chair 1" },
            { object = "v_res_fa_chair02", label = "Chair 2" },
            { object = "v_res_fh_barcchair", label = "High chair 2" },
            { object = "v_res_fh_dineeamesa", label = "Kitchen chair 1" },
            { object = "v_res_fh_dineeamesb", label = "Kitchen chair 2" },
            { object = "v_res_fh_dineeamesc", label = "Kitchen chair 3" },
            { object = "v_res_fh_easychair", label = "Chair 3" },
            { object = "v_res_fh_kitnstool", label = "Chair 4" },
            { object = "v_res_fh_singleseat", label = "High chair 3" },
            { object = "v_res_jarmchair", label = "Arm Chair" },
            { object = "v_res_j_dinechair", label = "Kitchen chair 4" },
            { object = "v_res_j_stool", label = "Chair 5" },
            { object = "v_res_mbchair", label = "MB Chair" },
            { object = "v_res_m_armchair", label = "Arm Chair 2" },
            { object = "v_res_m_dinechair", label = "Kitchen chair 5" },
            { object = "v_res_study_chair", label = "Study Chair" },
            { object = "v_res_trev_framechair", label = "Chair frame" },
            { object = "v_res_tre_chair", label = "Chair 6" },
            { object = "v_res_tre_officechair", label = "Office Chair" },
            { object = "v_res_tre_stool", label = "Chair 7" },
            { object = "v_res_tre_stool_leather", label = "Leather Chair" },
            { object = "v_res_tre_stool_scuz", label = "Chair Scuz" },
            { object = "v_med_p_deskchair", label = "Desk Chair" },
            { object = "v_med_p_easychair", label = "Easy Chair" },
            { object = "v_med_whickerchair1", label = "Whicker Chair" },
            { object = "prop_direct_chair_01", label = "Direct Chair" },
            { object = "prop_direct_chair_02", label = "Direct Chair 2" },
            { object = "prop_yacht_lounger", label = "Yacht Chair 1" },
            { object = "prop_yacht_seat_01", label = "Yacht Chair 2" },
            { object = "prop_yacht_seat_02", label = "Yacht Chair 3" },
            { object = "prop_yacht_seat_03", label = "Yacht Chair 4" },
            { object = "v_ret_chair_white", label = "White Chair" },
            { object = "v_ret_chair", label = "Chair 8" },
            { object = "v_ret_ta_stool", label = "TA Chair" },
            { object = "prop_cs_office_chair", label = "Office Chair 2" },
            { object = "apa_mp_h_yacht_armchair_01", label = "White Fauteuil" },
            { object = "v_club_barchair", label = "Chair 9" },
            { object = "prop_off_chair_04", label = "Desk Chair 2" },
            { object = "v_club_stagechair", label = "Fauteuil Roze" },
            { object = "v_club_officechair", label = "Desk Chair 3" },
            { object = "prop_armchair_01", label = "Sit Chair" },
            { object = "prop_bar_stool_01", label = "Barstool" },
            { object = "apa_mp_h_yacht_stool_01", label = "White Pouffe" },
            { object = "apa_mp_h_stn_chairarm_12", label = "Sitchair 3" },
            { object = "apa_mp_h_stn_chairstool_12", label = "Feet Support" },
            { object = "prop_chair_03", label = "Wooden Chair" },
            { object = "prop_couch_sm_05", label = "Corduroy Armchair" },
            { object = "prop_couch_sm_07", label = "White Armchair 2" },
            { object = "prop_couch_sm_02", label = "Orange Armchair" },
            { object = "apa_mp_h_stn_sofa_daybed_01", label = "Lounge Chair" },
            { object = "apa_mp_h_stn_sofa_daybed_02", label = "Lounge Chair 2" },
            { object = "apa_mp_h_din_chair_04", label = "Modern Chair" },
            { object = "apa_mp_h_din_chair_08", label = "Modern Chair 2" },
            { object = "apa_mp_h_din_chair_09", label = "Modern Chair 3" },
            { object = "apa_mp_h_din_chair_12", label = "Modern Chair 4" },
            { object = "apa_mp_h_din_stool_04", label = "Modern Chair 5" },
            { object = "apa_mp_h_stn_chairarm_01", label = "Modern Chair 6" },
            { object = "apa_mp_h_stn_chairarm_02", label = "Modern Chair 7" },
            { object = "apa_mp_h_stn_chairarm_03", label = "Modern Chair 8" },
            { object = "apa_mp_h_stn_chairarm_09", label = "Modern Chair 9" },
            { object = "apa_mp_h_stn_chairarm_11", label = "Modern Chair 10" },
            { object = "apa_mp_h_stn_chairarm_13", label = "Modern Chair 11" },
            { object = "apa_mp_h_stn_chairarm_24", label = "Modern Chair 12" },
            { object = "apa_mp_h_stn_chairarm_25", label = "Modern Chair 13" },
            { object = "apa_mp_h_stn_chairarm_26", label = "Modern Chair 14" },
            { object = "apa_mp_h_stn_chairstrip_04", label = "Modern Chair 15" },
            { object = "apa_mp_h_stn_chairstrip_05", label = "Modern Chair 16" },
            { object = "apa_mp_h_stn_chairstrip_08", label = "Modern Chair 17" },
            { object = "apa_mp_h_stn_foot_stool_01", label = "Pouffe" },
            { object = "apa_mp_h_stn_foot_stool_02", label = "Pouffe 2" },
            { object = "apa_mp_h_yacht_barstool_01", label = "Barstool 2" },
            { object = "ba_prop_int_glam_stool", label = "Barstool 3" },
            { object = "ba_prop_battle_club_chair_01", label = "Office Chair 3" },
            { object = "ba_prop_battle_club_chair_02", label = "Office Chair 4" },
            { object = "ba_prop_battle_club_chair_03", label = "Office Chair 5" },
            { object = "ba_prop_battle_control_seat", label = "Gaming Chair" },
        },
        
        Storage = {
            { object = "v_res_cabinet", label = "Cabinet Large" },
            { object = "v_res_d_dressingtable", label = "Dressing Table" },
            { object = "v_res_d_sideunit", label = "Side Unit" },
            { object = "v_res_fh_sidebrddine", label = "Side Unit" },
            { object = "v_res_fh_sidebrdlngb", label = "Side Unit" },
            { object = "v_res_mbbedtable", label = "Bed Unit" },
            { object = "v_res_j_tvstand", label = "Tv Unit" },
            { object = "v_res_mbdresser", label = "Dresser Unit" },
            { object = "v_res_mbottoman", label = "Bottoman Unit" },
            { object = "v_res_mconsolemod", label = "Console Unit" },
            { object = "v_res_mcupboard", label = "Cupboard Unit" },
            { object = "v_res_mdchest", label = "Chest Unit" },
            { object = "v_res_msoncabinet", label = "Mason Unit" },
            { object = "v_res_m_armoire", label = "Armoire Unit" },
            { object = "v_res_m_sidetable", label = "Side Unit" },
            { object = "v_res_son_desk", label = "Desk Unit" },
            { object = "v_res_tre_bedsidetable", label = "Side Unit" },
            { object = "v_res_tre_bedsidetableb", label = "Side Unit 2" },
            { object = "v_res_tre_smallbookshelf", label = "Book Unit" },
            { object = "v_res_tre_storageunit", label = "Storage Unit" },
            { object = "v_res_tre_wardrobe", label = "Wardrobe Unit" },
            { object = "v_res_tre_wdunitscuz", label = "Wood Unit" },
            { object = "prop_devin_box_closed", label = "Bean Bag 1" },
            { object = "prop_mil_crate_01", label = "Mil Crate 1" },
            { object = "prop_mil_crate_02", label = "Mil Crate 2" },
            { object = "prop_ld_int_safe_01", label = "Safe" },
            { object = "prop_toolchest_05", label = "Crafting Bench" },
            { object = "v_corp_filecablow", label = "Filing Cabinet Low" },
            { object = "v_corp_filecabtall", label = "Filing Cabinet High" },
            { object = "apa_mp_h_str_shelffloorm_02", label = "Large Modern Cupboard" },
            { object = "v_ilev_frnkwarddr1", label = "Cupboard Franklin" },
            { object = "prop_coathook_01", label = "Coat Rack" },
            { object = "v_corp_lowcabdark01", label = "Filing Cabinet Low Black" },
            { object = "v_corp_tallcabdark01", label = "Filing Cabinet High Black" },
            { object = "v_corp_cabshelves01", label = "Filing Cabinet Black" },
            { object = "v_corp_offshelf", label = "Filing Cabinet Groot" },
            { object = "v_61_lng_mesh_unitc", label = "Bookcase White" },
            { object = "ba_wardrobe", label = "Kledingkast" },
            { object = "apa_mp_h_str_sideboardl_06", label = "Cupboard Modern" },
            { object = "apa_mp_h_str_sideboardl_09", label = "Cupboard Modern 2" },
            { object = "apa_mp_h_str_shelfwallm_01", label = "Bookcase 2" },
            { object = "apa_mp_h_str_sideboardl_11", label = "Cupboard Modern 3" },
            { object = "imp_prop_impexp_parts_rack_03a", label = "Car Parts" },
            { object = "imp_prop_impexp_parts_rack_04a", label = "Car Parts 2" },
            { object = "imp_prop_impexp_parts_rack_05a", label = "Car Parts 3" },
            { object = "apa_mp_h_bed_chestdrawer_02", label = "Chest of Drawers" },
            { object = "hei_heist_bed_chestdrawer_04", label = "Chest of Drawers 2" },
            { object = "prop_rub_cabinet", label = "Rusted Filing Cabinet" },
            { object = "prop_tv_cabinet_03", label = "Tv Little Cupboard" },
            { object = "prop_tv_cabinet_04", label = "Tv Little Cupboard 2" },
            { object = "prop_tv_cabinet_05", label = "Tv Little Cupboard 3" },
            { object = "apa_mp_h_str_shelffreel_01", label = "Ikea Closet" },
            { object = "apa_mp_h_str_sideboardl_13", label = "Cabinet Modern 4" },
            { object = "apa_mp_h_str_sideboardl_14", label = "Cabinet Modern 5" },
            { object = "apa_mp_h_str_sideboardm_02", label = "Cabinet Modern 6" },
            { object = "bkr_prop_biker_garage_locker_01", label = "Biker Locker" },
            { object = "gr_prop_gr_bench_04b", label = "Biker Bench" },
        },        
        
        Electronics = {
            { object = "prop_trailr_fridge", label = "Old Fridge" },
            { object = "v_res_fh_speaker", label = "Speaker" },
            { object = "v_res_fh_speakerdock", label = "Speaker Dock" },
            { object = "v_res_fh_bedsideclock", label = "Bedside Clock" },
            { object = "v_res_fa_phone", label = "Phone" },
            { object = "v_res_fh_towerfan", label = "Tower Fan" },
            { object = "v_res_fa_fan", label = "Fan" },
            { object = "v_res_lest_bigscreen", label = "Bigscreen" },
            { object = "v_res_lest_monitor", label = "Monitor" },
            { object = "v_res_tre_mixer", label = "Mixer" },
            { object = "prop_cs_cctv", label = "CCTV" },
            { object = "prop_ld_lap_top", label = "Laptop" },
            { object = "prop_ld_monitor_01", label = "Monitor" },
            { object = "prop_speaker_05", label = "Mounted Speaker" },
            { object = "prop_tv_flat_03b", label = "Small Flatscreen" },
            { object = "prop_laptop_01a", label = "Open Laptop" },
            { object = "prop_tv_flat_michael", label = "Hanging Flatscreen" },
            { object = "prop_dyn_pc", label = "PC" },
            { object = "prop_keyboard_01b", label = "Keyboard" },
            { object = "prop_mouse_01b", label = "Computer Mouse" },
            { object = "v_ret_gc_phone", label = "Office Phone" },
            { object = "prop_tv_flat_01", label = "Large Flatscreen" },
            { object = "prop_arcade_01", label = "Arcade Machine" },
            { object = "prop_console_01", label = "Game Console" },
            { object = "v_res_tre_dvdplayer", label = "DVD Player" },
            { object = "prop_speaker_08", label = "Wooden Speaker" },
            { object = "prop_cctv_mon_02", label = "CCTV Monitor" },
            { object = "prop_tv_flat_02", label = "Standing Flatscreen" },
            { object = "prop_cctv_cam_01a", label = "CCTV Camera 1" },
            { object = "prop_dest_cctv_02", label = "CCTV Monitor 2" },
            { object = "prop_cctv_cam_07a", label = "CCTV Camera 2" },
            { object = "apa_mp_h_str_avunits_04", label = "Flat Screen Furniture 1" },
            { object = "apa_mp_h_str_avunits_01", label = "Flat Screen Furniture 2" },
            { object = "v_club_vu_deckcase", label = "DJ Set" },
            { object = "v_corp_servercln", label = "Server Rack" },
            { object = "apa_mp_h_str_avunitl_01_b", label = "Flat Screen Furniture 3" },
            { object = "apa_mp_h_str_avunitl_04", label = "Flat Screen Furniture 4" },
            { object = "apa_mp_h_str_avunitm_01", label = "Flat Screen Furniture 5" },
            { object = "apa_mp_h_str_avunitm_03", label = "Flat Screen Furniture 6" },
            { object = "v_res_printer", label = "Printer" },
            { object = "apa_mp_h_acc_phone_01", label = "Old-Fashioned Telephone" },
            { object = "v_res_mousemat", label = "Mouse Pad" },
            { object = "v_res_pcheadset", label = "Headset" },
            { object = "v_res_pcspeaker", label = "PC Speaker" },
            { object = "ba_prop_battle_club_speaker_small", label = "Small Speaker" },
            { object = "ba_prop_battle_club_speaker_med", label = "Medium Speaker" },
            { object = "ba_prop_battle_club_speaker_large", label = "Large Speaker" },
            { object = "v_res_pcwoofer", label = "PC Subwoofer" },
            { object = "prop_controller_01", label = "Controller" },
            { object = "prop_cs_remote_01", label = "Remote Control" },
            { object = "prop_portable_hifi_01", label = "Radio" },
            { object = "prop_dj_deck_02", label = "DJ Table" },
            { object = "prop_speaker_01", label = "Speaker" },
        },
        
        Beds = {
            { object = "v_res_d_bed", label = "Bed 1" },
            { object = "v_res_lestersbed", label = "Bed 2" },
            { object = "v_res_mbbed", label = "MB Bed" },
            { object = "v_res_mdbed", label = "MD Bed" },
            { object = "v_res_msonbed", label = "Bed 3" },
            { object = "v_res_tre_bed1", label = "Bed 4" },
            { object = "v_res_tre_bed2", label = "T Bed" },
            { object = "v_res_tt_bed", label = "TT Bed" },
            { object = "apa_mp_h_bed_with_table_02", label = "Fancy Bed" },
            { object = "apa_mp_h_bed_wide_05", label = "Red Bed" },
            { object = "apa_mp_h_bed_double_08", label = "Square Bed" },
            { object = "apa_mp_h_bed_double_09", label = "Modern Bed" },
            { object = "apa_mp_h_yacht_bed_01", label = "California King" },
            { object = "apa_mp_h_yacht_bed_02", label = "California King 2" },
            { object = "bkr_prop_biker_campbed_01", label = "Camp Bed" },
            { object = "ex_prop_exec_bed_01", label = "Small Bed" },
            { object = "gr_prop_bunker_bed_01", label = "Klein Bed 2" },
            { object = "p_mbbed_s", label = "Bed 5" },
        },

        Lighting = {
            { object = "v_corp_cd_desklamp", label = "Desk Corp Lamp" },
            { object = "v_res_desklamp", label = "Desk Lamp" },
            { object = "v_res_d_lampa", label = "Lamp AA" },
            { object = "v_res_fa_lamp1on", label = "Lamp 1" },
            { object = "v_res_fh_floorlamp", label = "Floor Lamp" },
            { object = "v_res_fh_lampa_on", label = "Lamp 2" },
            { object = "v_res_j_tablelamp1", label = "Table Lamp" },
            { object = "v_res_j_tablelamp2", label = "Table Lamp 2" },
            { object = "v_res_mdbedlamp", label = "Bed Lamp" },
            { object = "v_res_mplanttongue", label = "Plant Tongue Lamp" },
            { object = "v_res_mtblelampmod", label = "Table Lamp 3" },
            { object = "v_res_m_lampstand", label = "Lamp Stand" },
            { object = "v_res_m_lampstand2", label = "Lamp Stand 2" },
            { object = "v_res_m_lamptbl", label = "Table Lamp 4" },
            { object = "v_res_tre_lightfan", label = "Light Fan" },
            { object = "v_res_tre_talllamp", label = "Tall Lamp" },
            { object = "v_ret_fh_walllighton", label = "Wall Light" },
            { object = "v_ret_gc_lamp", label = "GC Lamp" },
            { object = "prop_dummy_light", label = "Flickering Light" },
            { object = "prop_ld_cont_light_01", label = "Side Wall Light" },
            { object = "V_44_D_emis", label = "Test Light" },
            { object = "prop_wall_light_07a", label = "Lantaarn" },
            { object = "prop_wall_light_01a", label = "Cheap Lamp" },
            { object = "v_serv_tu_light2_", label = "Industrieel Licht" },
            { object = "v_serv_tu_light3_", label = "Industrieel Licht 2" },
            { object = "ba_prop_battle_lights_ceiling_l_a", label = "Hanging Lamp" },
            { object = "v_med_p_floorlamp", label = "Big Lamp" },
            { object = "v_club_vu_lamp", label = "Small Lamp" },
            { object = "ba_prop_battle_lights_wall_l_a", label = "Wall Lamp" },
            { object = "ba_prop_battle_lights_ceiling_l_c", label = "Hanging Lamp 2" },
            { object = "ba_prop_battle_lights_ceiling_l_b", label = "Kroonluchter 2" },
            { object = "ba_prop_battle_lights_wall_l_c", label = "Wall Lamp 2" },
            { object = "ba_prop_battle_lights_wall_l_b", label = "Wall Lamp 3" },
            { object = "hei_heist_lit_lightpendant_02", label = "Hanging Lamp 3" },
            { object = "prop_oldlight_01b", label = "Wall Lamp 4" },
            { object = "apa_mp_h_lit_floorlampnight_07", label = "Blue Lamp" },
            { object = "apa_mp_h_ceiling_light_01", label = "Commercial" },
            { object = "apa_mp_h_ceiling_light_01_day", label = "Commercial 2" },
            { object = "apa_mp_h_ceiling_light_02", label = "Ceiling Light" },
            { object = "apa_mp_h_ceiling_light_02_day", label = "Ceiling Light 2" },
            { object = "ba_prop_battle_lights_ceiling_l_d", label = "Commercial 3" },
            { object = "ba_prop_battle_lights_ceiling_l_f", label = "Ceiling Light 3" },
            { object = "ba_prop_battle_lights_ceiling_l_e", label = "Ceiling Light 4" },
            { object = "apa_mp_h_floorlamp_a", label = "Floor Lamp" },
            { object = "apa_mp_h_floorlamp_b", label = "Floor Lamp 2" },
            { object = "apa_mp_h_floorlamp_c", label = "Floor Lamp 3" },
            { object = "apa_mp_h_floor_lamp_int_08", label = "Floor Lamp 4" },
            { object = "apa_mp_h_lampbulb_multiple_a", label = "Ceiling Light 5" },
            { object = "apa_mp_h_lit_floorlamp_02", label = "Floor Lamp 5" },
            { object = "apa_mp_h_lit_floorlampnight_14", label = "Floor Lamp 6" },
            { object = "apa_mp_h_lit_floorlamp_03", label = "Floor Lamp 7" },
            { object = "apa_mp_h_lit_floorlamp_06", label = "Floor Lamp 8" },
            { object = "apa_mp_h_lit_floorlamp_10", label = "Floor Lamp 9" },
            { object = "apa_mp_h_lit_floorlamp_13", label = "Floor Lamp 10" },
            { object = "apa_mp_h_lit_floorlamp_17", label = "Floor Lamp 11" },
            { object = "apa_mp_h_lit_lamptablenight_16", label = "Night Light" },
            { object = "apa_mp_h_lit_lamptablenight_24", label = "Night Light 2" },
            { object = "apa_mp_h_lit_lamptable_005", label = "Night Light 3" },
            { object = "apa_mp_h_lit_lamptable_04", label = "Night Light 4" },
            { object = "apa_mp_h_lit_lamptable_09", label = "Night Light 5" },
            { object = "apa_mp_h_lit_lamptable_14", label = "Night Light 6" },
            { object = "apa_mp_h_lit_lamptable_17", label = "Night Light 7" },
            { object = "apa_mp_h_yacht_table_lamp_01", label = "Night Light 8" },
        },

        Tables = {
            { object = "v_res_d_coffeetable", label = "Coffee Table 1" },
            { object = "v_res_d_roundtable", label = "Round Table" },
            { object = "v_res_d_smallsidetable", label = "Small Side Table" },
            { object = "v_res_fh_coftablea", label = "Table A" },
            { object = "v_res_fh_coftableb", label = "Table B" },
            { object = "v_res_fh_coftbldisp", label = "Table C" },
            { object = "v_res_fh_diningtable", label = "Dining Table" },
            { object = "v_res_j_coffeetable", label = "Coffee Table 2" },
            { object = "v_res_j_lowtable", label = "Low Table" },
            { object = "v_res_mdbedtable", label = "Bed Table" },
            { object = "v_res_mddesk", label = "Desk" },
            { object = "v_res_msidetblemod", label = "Side Table" },
            { object = "v_res_m_console", label = "Console Table" },
            { object = "v_res_m_dinetble_replace", label = "Dining Table 2" },
            { object = "v_res_m_h_console", label = "Console H Table" },
            { object = "v_res_m_stool", label = "Stool?" },
            { object = "v_res_tre_sideboard", label = "Sideboard Table" },
            { object = "v_res_tre_table2", label = "Table 2" },
            { object = "v_res_tre_tvstand", label = "Tv Table" },
            { object = "v_res_tre_tvstand_tall", label = "Tv Table Tall" },
            { object = "v_med_p_coffeetable", label = "Med Coffee Table" },
            { object = "v_med_p_desk", label = "Med Desk" },
            { object = "prop_yacht_table_01", label = "Yacht Table 1" },
            { object = "prop_yacht_table_02", label = "Yacht Table 2" },
            { object = "prop_yacht_table_03", label = "Yacht Table 3" },
            { object = "v_ret_csr_table", label = "CSR Table" },
            { object = "v_res_mconsoletrad", label = "High Side Table" },
            { object = "v_ilev_liconftable_sml", label = "Office Table" },
            { object = "v_ret_tablesml", label = "Side Table Marillaux" },
            { object = "apa_mp_h_yacht_coffee_table_02", label = "Koffie Table Brown" },
            { object = "apa_mp_h_yacht_side_table_01", label = "Side Table Brown" },
            { object = "apa_mp_h_yacht_side_table_02", label = "Ronde Side Table" },
            { object = "apa_mp_h_tab_sidelrg_04", label = "Ronde Side Table 2" },
            { object = "v_club_vu_table", label = "Covered Table" },
            { object = "apa_mp_h_tab_sidelrg_07", label = "Koffie Table Glas" },
            { object = "bkr_prop_weed_table_01b", label = "Clap Table" },
            { object = "ba_prop_int_trad_table", label = "Stand Table" },
            { object = "apa_mp_h_str_sideboards_02", label = "Side Table Glas" },
            { object = "apa_mp_h_yacht_coffee_table_01", label = "Koffie Table Modern" },
            { object = "apa_mp_h_din_table_04", label = "Dinner Table Glas" },
            { object = "xm_prop_base_staff_desk_01", label = "Desk + Setup" },
            { object = "apa_mp_h_tab_coffee_07", label = "Triangular Side Table" },
            { object = "apa_mp_h_tab_coffee_08", label = "White Side Table" },
            { object = "apa_mp_h_tab_sidelrg_01", label = "Glass Side Table" },
            { object = "apa_mp_h_tab_sidelrg_02", label = "Glass Side Table 2" },
            { object = "apa_mp_h_tab_sidesml_01", label = "Folding Table" },
            { object = "ba_prop_int_edgy_table_01", label = "Table Marble" },
            { object = "ba_prop_int_edgy_table_02", label = "Table Marble High" },
            { object = "xm_prop_lab_desk_01", label = "Lab Table" },
        },

        Bathroom = {
            { object = "prop_ld_toilet_01", label = "Toilet 1" },
            { object = "prop_toilet_01", label = "Toilet 2" },
            { object = "prop_toilet_02", label = "Toilet 3" },
            { object = "prop_sink_02", label = "Sink 1" },
            { object = "prop_sink_04", label = "Sink 2" },
            { object = "prop_sink_05", label = "Sink 3" },
            { object = "prop_sink_06", label = "Sink 4" },
            { object = "prop_soap_disp_01", label = "Soap Dispenser" },
            { object = "prop_shower_rack_01", label = "Shower Rack" },
            { object = "prop_handdry_01", label = "Hand Dryer 1" },
            { object = "prop_handdry_02", label = "Hand Dryer 2" },
            { object = "prop_towel_rail_01", label = "Towel Rail 1" },
            { object = "prop_towel_rail_02", label = "Towel Rail 2" },
            { object = "prop_towel_01", label = "Towel 1" },
            { object = "v_res_mbtowel", label = "Towel 2" },
            { object = "v_res_mbtowelfld", label = "Towel 3" },
            { object = "v_res_mbath", label = "Bath" },
            { object = "v_res_mbsink", label = "Sink" },
            { object = "v_ilev_mm_faucet", label = "Tap" },
            { object = "v_res_tre_washbasket", label = "Washing Mand" },
            { object = "prop_toilet_soap_02", label = "Tray Soap" },
            { object = "prop_bar_sink_01", label = "Sink" },
            { object = "apa_mp_h_bathtub_01", label = "Bath" },
            { object = "prop_toilet_brush_01", label = "Brush" },
            { object = "prop_toilet_roll_01", label = "Toilet Rol" },
            { object = "prop_toilet_roll_02", label = "Toilet Rol 2" },
            { object = "prop_toilet_shamp_01", label = "Shampoo" },
            { object = "prop_toilet_shamp_02", label = "Shampoo 2" },
        },

        Decorations = {
            { object = "apa_p_h_acc_artwalll_02", label = "Painting whit marks" },
            { object = "v_ind_cs_toolboard", label = "Tools" },
            { object = "apa_mp_stilts_bed_art", label = "3d art" },
            { object = "ex_office_swag_paintings03", label = "Paintingen Ground" },
            { object = "ex_mp_h_acc_artwallm_03", label = "abstract Painting" },
            { object = "ex_p_h_acc_artwallm_04", label = "abstract Painting 2" },
            { object = "ex_p_h_acc_artwalll_01", label = "abstract Painting Big" },
            { object = "apa_p_h_acc_artwalll_03", label = "abstract Painting 3" },
            { object = "ex_mp_h_acc_artwallm_02", label = "abstract Painting 4" },
            { object = "ex_p_h_acc_artwallm_03", label = "abstract Painting 5" },
            { object = "apa_mp_stilts_a_study_pics", label = "Paintingen" },
            { object = "apa_mp_h_acc_artwallm_02", label = "abstract Painting 6" },
            { object = "apa_mp_h_acc_artwalll_02", label = "abstract Painting 7" },
            { object = "apa_mp_h_acc_artwallm_04", label = "abstract Painting 8" },
            { object = "prop_dart_bd_cab_01", label = "Dartboard" },
            { object = "prop_dart_bd_01", label = "Dartboard 2" },
            { object = "hei_heist_acc_artwalll_01", label = "wall deco 1" },
            { object = "hei_heist_acc_artgolddisc_01", label = "wall deco 2" },
            { object = "hei_heist_acc_artgolddisc_02", label = "wall deco 3" },
            { object = "hei_heist_acc_artgolddisc_03", label = "wall deco 4" },
            { object = "hei_heist_acc_artgolddisc_04", label = "wall deco 5" },
            { object = "v_ilev_ra_doorsafe", label = "Luxury deco" },
        },

        Kitchen = {
            { object = "prop_washer_01", label = "Washer 1" },
            { object = "prop_washer_02", label = "Washer 2" },
            { object = "prop_washer_03", label = "Washer 3" },
            { object = "prop_washing_basket_01", label = "Washing Basket" },
            { object = "v_res_fridgemoda", label = "Fridge 1" },
            { object = "v_res_fridgemodsml", label = "Fridge 2" },
            { object = "prop_fridge_01", label = "Fridge 3" },
            { object = "prop_fridge_03", label = "Fridge 4" },
            { object = "prop_cooker_03", label = "Cooker" },
            { object = "prop_micro_01", label = "Microwave 1" },
            { object = "prop_micro_02", label = "Microwave 2" },
            { object = "prop_wok", label = "Wok" },
            { object = "v_res_cakedome", label = "Cake Plate" },
            { object = "v_res_fa_chopbrd", label = "Chopping Board" },
            { object = "v_res_mutensils", label = "Utensils" },
            { object = "v_res_pestle", label = "Pestle" },
            { object = "v_ret_ta_paproll", label = "PaperRoll 1" },
            { object = "v_ret_ta_paproll2", label = "PaperRoll 2" },
            { object = "v_ret_fh_pot01", label = "Pot 1" },
            { object = "v_ret_fh_pot02", label = "Pot 2" },
            { object = "v_ret_fh_pot05", label = "Pot 3" },
            { object = "prop_pot_03", label = "Pot 4" },
            { object = "prop_pot_04", label = "Pot 5" },
            { object = "prop_pot_05", label = "Pot 6" },
            { object = "prop_pot_06", label = "Pot 7" },
            { object = "prop_pot_rack", label = "Pot Rack" },
            { object = "prop_kitch_juicer", label = "Juicer" },
            { object = "v_res_ovenhobmod", label = "Stove" },
            { object = "v_res_mkniferack", label = "Knive" },
            { object = "v_res_mchopboard", label = "Cutting plank" },
            { object = "prop_cs_kitchen_cab_l", label = "Kitchen Cupboard Wide" },
            { object = "prop_cs_kitchen_cab_r", label = "Kitchen cupboard smal" },
            { object = "prop_cs_kitchen_cab_r", label = "Kitchen cupboard smal" },
            { object = "v_res_tre_fridge", label = "refrigerator" },
            { object = "apa_mp_h_acc_coffeemachine_01", label = "coffee machine" },
            { object = "p_new_j_counter_02", label = "Counter" },
            { object = "prop_bar_pump_09", label = "Pump 1" },
            { object = "prop_bar_pump_01", label = "Pump 2" },
            { object = "prop_chip_fryer", label = "Chips fryer" },
            { object = "prop_cleaver", label = "Knife" },
            { object = "prop_coffee_mac_02", label = "coffee machine" },
            { object = "prop_coffee_mac_01", label = "coffee machine 2" },
            { object = "prop_cs_fork", label = "Fork" },
            { object = "prop_cs_sink_filler", label = "Sink filler" },
            { object = "prop_toaster_01", label = "Toaster" },
            { object = "prop_cs_plate_01", label = "Plate" },
            { object = "prop_foodprocess_01", label = "Food Process" },
            { object = "prop_food_sugarjar", label = "Sugar Bowl" },
            { object = "prop_juice_dispenser", label = "Dispencer" },
            { object = "prop_knife_stand", label = "Knife holder" },
            { object = "prop_knife", label = "Knife 2" },
            { object = "prop_micro_04", label = "Microwave 4" },
            { object = "v_ret_fh_plate3", label = "Plate 5" },
            { object = "v_ilev_tt_plate01", label = "Plate 6" },
            { object = "v_res_fa_grater", label = "Grater" },
            { object = "v_res_tt_pizzaplate", label = "Pizza Plate" },
            { object = "v_ret_247_ketchup2", label = "Ketchup" },
        },

        Plants = {
            { object = "prop_fib_plant_01", label = "Plant Fib" },
            { object = "v_corp_bombplant", label = "Plant Bomb" },
            { object = "v_res_mflowers", label = "Plant Flowers" },
            { object = "v_res_mvasechinese", label = "Plant Chinese" },
            { object = "v_res_m_bananaplant", label = "Plant Banana" },
            { object = "v_res_m_palmplant1", label = "Plant Palm" },
            { object = "v_res_m_palmstairs", label = "Plant Palm 2" },
            { object = "v_res_m_urn", label = "Plant Urn" },
            { object = "v_res_rubberplant", label = "Plant Rubber" },
            { object = "v_res_tre_plant", label = "Plant" },
            { object = "v_res_tre_tree", label = "Plant Tree" },
            { object = "v_med_p_planter", label = "Planter" },
            { object = "v_ret_flowers", label = "Flowers" },
            { object = "v_ret_j_flowerdisp", label = "Flowers 1" },
            { object = "v_ret_j_flowerdisp_white", label = "Flowers 2" },
            { object = "v_res_m_vasefresh", label = "FlowerFase" },
            { object = "v_res_rosevasedead", label = "Pink Fase 2" },
            { object = "v_res_exoticvase", label = "FlowerFase 2" },
            { object = "v_res_rosevase", label = "Pink Fase" },
            { object = "prop_pot_plant_6a", label = "Hanging ende plant" },
            { object = "prop_pot_plant_02a", label = "Flower pot" },
            { object = "apa_mp_h_acc_plant_palm_01", label = "palm plant" },
            { object = "prop_plant_interior_05a", label = "flower box" },
            { object = "prop_plant_int_01a", label = "plant" },
            { object = "prop_plant_int_01b", label = "plant 2" },
            { object = "prop_plant_int_02a", label = "plant 3" },
            { object = "prop_plant_int_02b", label = "plant 4" },
            { object = "prop_plant_int_03a", label = "plant 5" },
            { object = "prop_plant_int_03b", label = "plant 6" },
            { object = "prop_plant_int_03c", label = "plant 7" },
            { object = "prop_plant_int_04a", label = "plant 8" },
            { object = "prop_plant_int_04c", label = "plant 9" },
            { object = "prop_plant_int_05b", label = "flower box 2" },
            { object = "prop_pot_plant_01a", label = "plant pot 2" },
            { object = "prop_pot_plant_01b", label = "plant pot 3" },
            { object = "prop_pot_plant_01c", label = "plant pot 4" },
            { object = "prop_pot_plant_01d", label = "plant pot 5" },
            { object = "prop_pot_plant_01e", label = "plant pot 6" },
            { object = "prop_pot_plant_03b", label = "plant pot 7" },
            { object = "prop_pot_plant_05a", label = "plant pot 8" },
            { object = "prop_pot_plant_05b", label = "plant pot 9" },
            { object = "p_int_jewel_plant_01", label = "plant pot 10" },
            { object = "p_int_jewel_plant_02", label = "plant pot 11" },
            { object = "apa_mp_h_acc_vase_flowers_01", label = "plant pot 12" },
            { object = "apa_mp_h_acc_vase_flowers_02", label = "plant pot 13" },
            { object = "apa_mp_h_acc_vase_flowers_03", label = "plant pot 14" },
            { object = "apa_mp_h_acc_vase_flowers_04", label = "plant pot 15" },
        },
        
        Detailing = {
            { object = "v_res_r_figcat", label = "Fig Cat" },
            { object = "v_res_r_figclown", label = "Fig Clown" },
            { object = "v_res_r_figauth2", label = "Fig Auth" },
            { object = "v_res_r_figfemale", label = "Fig Female" },
            { object = "v_res_r_figflamenco", label = "Fig Flamenco" },
            { object = "v_res_r_figgirl", label = "Fig Girl" },
            { object = "v_res_r_figgirlclown", label = "Fig Girl Clown" },
            { object = "v_res_r_figoblisk", label = "Fig Oblisk" },
            { object = "v_res_r_figpillar", label = "Fig Pillar" },
            { object = "v_res_r_teapot", label = "Teapot" },
            { object = "v_res_sculpt_dec", label = "Sculpture 1" },
            { object = "v_res_sculpt_decd", label = "Sculpture 2" },
            { object = "v_res_sculpt_dece", label = "Sculpture 3" },
            { object = "v_res_sculpt_decf", label = "Sculpture 4" },
            { object = "v_res_skateboard", label = "Skateboard" },
            { object = "v_res_sketchpad", label = "Sketchpad" },
            { object = "v_res_tissues", label = "Tissues" },
            { object = "v_res_tre_basketmess", label = "Basket" },
            { object = "v_res_tre_bin", label = "Bin" },
            { object = "v_res_tre_cushiona", label = "Cushion 1" },
            { object = "v_res_tre_cushionb", label = "Cushion 2" },
            { object = "v_res_tre_cushionc", label = "Cushion 3" },
            { object = "v_res_tre_cushiond", label = "Cushion 4" },
            { object = "v_res_tre_cushnscuzb", label = "Cushion 5" },
            { object = "v_res_tre_cushnscuzd", label = "Cushion 6" },
            { object = "v_res_tre_fruitbowl", label = "Fruitbowl" },
            { object = "v_med_p_sideboard", label = "Sideboard" },
            { object = "prop_idol_01", label = "Idol 1" },
            { object = "v_res_r_fighorsestnd", label = "Figurine black horse" },
            { object = "v_res_r_fighorse", label = "Figurine big horse" },
            { object = "v_res_r_figdancer", label = "Figurine dancer" },
            { object = "v_res_fa_idol02", label = "Olifanten Figurine" },
            { object = "v_res_m_statue", label = "Sculpture" },
            { object = "v_20_ornaeagle", label = "Figurine adelaar" },
            { object = "v_med_p_vaseround", label = "Fase round" },
            { object = "ex_mp_h_acc_vase_05", label = "Fase Violet" },
            { object = "apa_mp_h_acc_dec_head_01", label = "Art work" },
            { object = "apa_mp_h_acc_dec_sculpt_02", label = "Art work 2" },
            { object = "ex_mp_h_acc_dec_plate_02", label = "Art work 3" },
            { object = "apa_mp_h_acc_bowl_ceramic_01", label = "Schaal" },
            { object = "apa_mp_h_acc_dec_plate_01", label = "Scale 2" },
            { object = "apa_mp_h_acc_vase_01", label = "Vase black and white" },
            { object = "apa_mp_h_acc_vase_02", label = "Vase red" },
            { object = "apa_mp_h_acc_vase_05", label = "Vase" },
            { object = "apa_mp_h_acc_vase_06", label = "Vase black and white 2" },
        },

        Misc = {
            { object = "v_corp_facebeanbag", label = "Bean Bag 1" },
            { object = "v_res_cherubvase", label = "White Vase" },
            { object = "v_res_d_paddedwall", label = "Padded Wall" },
            { object = "v_res_d_ramskull", label = "Item" },
            { object = "v_res_d_whips", label = "Whips" },
            { object = "v_res_fashmag1", label = "Mags" },
            { object = "v_res_fashmagopen", label = "Mags Open" },
            { object = "v_res_fa_magtidy", label = "Mag Tidy" },
            { object = "v_res_fa_yogamat002", label = "Yoga Mat 1" },
            { object = "v_res_fa_yogamat1", label = "Yoga Mat 2" },
            { object = "v_res_fh_aftershavebox", label = "Aftershave" },
            { object = "v_res_fh_flowersa", label = "Flowers" },
            { object = "v_res_fh_fruitbowl", label = "Fruitbowl" },
            { object = "v_res_fh_laundrybasket", label = "Laundry Basket" },
            { object = "v_res_fh_pouf", label = "Pouf" },
            { object = "v_res_fh_sculptmod", label = "Sculpture" },
            { object = "v_res_j_magrack", label = "Mag Rack" },
            { object = "v_res_jewelbox", label = "Jewel Box" },
            { object = "v_res_mbbin", label = "Bin" },
            { object = "v_res_mbowlornate", label = "Ornate Bowl" },
            { object = "v_res_mbronzvase", label = "Bronze Vase" },
            { object = "v_res_mchalkbrd", label = "Chalk Board" },
            { object = "v_res_mddresser", label = "Dresser" },
            { object = "v_res_mplinth", label = "Linth" },
            { object = "v_res_mp_ashtrayb", label = "Ashtray" },
            { object = "v_res_m_candle", label = "Candle" },
            { object = "v_res_m_candlelrg", label = "Candle Large" },
            { object = "v_res_m_kscales", label = "Scales" },
            { object = "v_res_tt_bedpillow", label = "Bed Pillow" },
            { object = "v_med_cor_whiteboard", label = "Whiteboard" },
            { object = "prop_ashtray_01", label = "Asbak Black" },
            { object = "v_ret_fh_ashtray", label = "Asbak Stone" },
            { object = "v_24_wdr_mesh_rugs", label = "Rag" },
            { object = "apa_mp_h_acc_rugwooll_04", label = "Rug 2" },
            { object = "ex_mp_h_acc_rugwoolm_04", label = "Rug 3" },
            { object = "apa_mp_h_acc_rugwoolm_03", label = "Rug 4" },
            { object = "apa_mp_h_acc_rugwooll_03", label = "Rug 5" },
            { object = "apa_mp_h_acc_rugwoolm_04", label = "Rug 6" },
            { object = "v_club_rack", label = "Kledingrek" },
            { object = "prop_a4_pile_01", label = "A4 Pile" },
            { object = "prop_amb_40oz_03", label = "40 oz" },
            { object = "prop_amb_beer_bottle", label = "Beer" },
            { object = "prop_aviators_01", label = "Aviators" },
            { object = "prop_barry_table_detail", label = "Detail" },
            { object = "prop_beer_box_01", label = "Beers" },
            { object = "prop_binoc_01", label = "Binoculars" },
            { object = "prop_blox_spray", label = "Blox Spray" },
            { object = "prop_bongos_01", label = "Bongos" },
            { object = "prop_bong_01", label = "Bong" },
            { object = "prop_boombox_01", label = "Boombox" },
            { object = "prop_bowl_crisps", label = "Bowl Crisps" },
            { object = "prop_candy_pqs", label = "Candy" },
            { object = "prop_carrier_bag_01", label = "Carrier Bag" },
            { object = "prop_ceramic_jug_01", label = "Ceramic Jug" },
            { object = "prop_cigar_pack_01", label = "Cigar Pack 1" },
            { object = "prop_cigar_pack_02", label = "Cigar Pack 2" },
            { object = "prop_cs_beer_box", label = "Beer Box 2" },
            { object = "prop_cs_binder_01", label = "Binder" },
            { object = "prop_cs_bs_cup", label = "Cup" },
            { object = "prop_cs_cashenvelope", label = "Envelope" },
            { object = "prop_cs_champ_flute", label = "Flute" },
            { object = "prop_cs_duffel_01", label = "Duffel Bag" },
            { object = "prop_cs_dvd", label = "DVD" },
            { object = "prop_cs_dvd_case", label = "DVD Case" },
            { object = "prop_cs_film_reel_01", label = "Film Reel" },
            { object = "prop_cs_ilev_blind_01", label = "Blind" },
            { object = "p_ld_bs_bag_01", label = "Bag" },
            { object = "prop_cs_ironing_board", label = "Ironing Board" },
            { object = "prop_cs_katana_01", label = "Katana" },
            { object = "prop_cs_kettle_01", label = "Kettle" },
            { object = "prop_cs_lester_crate", label = "Crate" },
            { object = "prop_cs_petrol_can", label = "Petrol Can" },
            { object = "prop_cs_sack_01", label = "Sack" },
            { object = "prop_cs_script_bottle_01", label = "Script Bottle" },
            { object = "prop_cs_script_bottle", label = "Script Bottle 2" },
            { object = "prop_cs_street_binbag_01", label = "Bin Bag" },
            { object = "prop_cs_whiskey_bottle", label = "Whiskey Bottle" },
            { object = "prop_sh_bong_01", label = "Bong" },
            { object = "prop_peanut_bowl_01", label = "Peanuts" },
            { object = "prop_tumbler_01", label = "Tumbler" },
            { object = "prop_weed_bottle", label = "Weed Koker" },
            { object = "p_cs_lighter_01", label = "Lighter" },
            { object = "p_cs_papers_01", label = "Rolling Papers" },
            { object = "v_res_d_dildo_f", label = "Dildo Black" },
            { object = "v_res_d_dildo_c", label = "Dildo White" },
            { object = "v_res_d_dildo_a", label = "Mommy's Toy" },
            { object = "prop_champ_cool", label = "Champagne Cooler" },
            { object = "prop_champ_01b", label = "Champagne Bottle" },
            { object = "prop_champ_flute", label = "Champagne Glass" },
            { object = "ba_prop_club_champset", label = "Champagne Set" },
            { object = "v_res_fa_candle01", label = "Candle Blue" },
            { object = "v_res_fa_candle02", label = "Candle Red" },
            { object = "v_res_fa_candle03", label = "Candle Black" },
            { object = "v_res_fa_candle04", label = "Candle Small" },
            { object = "v_med_bottles2", label = "Chemicals" },
            { object = "v_res_desktidy", label = "Office Stuff" },
            { object = "v_med_p_notebook", label = "Note's" },
            { object = "bkr_prop_weed_dry_01a", label = "Mountain of Weed" },
            { object = "ba_prop_battle_trophy_battler", label = "Fist Trophy" },
            { object = "ba_prop_battle_trophy_no1", label = "Ster Trophy" },
            { object = "prop_golf_bag_01c", label = "Golf Bag" },
            { object = "hei_heist_kit_bin_01", label = "Garbage Can" },
            { object = "prop_wooden_barrel", label = "Wooden Vat" },
            { object = "bkr_prop_bkr_cash_scatter_01", label = "Scatter" },
            { object = "bkr_prop_bkr_cashpile_01", label = "Cash" },
            { object = "bkr_prop_bkr_cash_roll_01", label = "Cash Roll" },
            { object = "bkr_prop_bkr_cashpile_04", label = "Pile of Cash" },
            { object = "bkr_prop_weed_bigbag_open_01a", label = "Weed Open Bag" },
            { object = "bkr_prop_weed_bigbag_02a", label = "Weed Bag 2" },
            { object = "bkr_prop_weed_bigbag_03a", label = "Weed Bag 3" },
            { object = "bkr_prop_weed_scales_01a", label = "Scales" },
            { object = "bkr_prop_weed_smallbag_01a", label = "Small Bag" },
            { object = "prop_gold_bar", label = "Gold Bar" },
            { object = "beerrow_world", label = "Beer Bottles" },
            { object = "beerrow_local", label = "Beer Bottles 2" },
            { object = "p_cs_bbbat_01", label = "Bat" },
            { object = "p_cs_cuffs_02_s", label = "Handcuffs" },
            { object = "p_cs_joint_02", label = "Joint" },
            { object = "p_ing_coffeecup_01", label = "Coffee mug" },
            { object = "p_tumbler_cs2_s", label = "Tumbler" },
            { object = "prop_turkey_leg_01", label = "Chicken leg" },
            { object = "prop_amb_donut", label = "Donut" },
            { object = "prop_donut_02", label = "Donut 2" },
            { object = "prop_bar_shots", label = "Bar shots" },
            { object = "prop_bar_stirrers", label = "Bar stirrers" },
            { object = "prop_beer_amopen", label = "Beer open" },
            { object = "prop_beer_blr", label = "Beer 1" },
            { object = "prop_beer_logger", label = "Beer 2" },
            { object = "prop_beer_stzopen", label = "Beer 3" },
            { object = "prop_bikerset", label = "Biker Set" },
            { object = "prop_bottle_brandy", label = "Bottle brandy" },
            { object = "prop_tequila_bottle", label = "Tequila bottle" },
            { object = "prop_tequila", label = "Tequila" },
            { object = "prop_bottle_cognac", label = "Bottle of Cognac" },
            { object = "prop_bottle_macbeth", label = "Bottle of Macbeth" },
            { object = "prop_brandy_glass", label = "Brandy Glass" },
            { object = "prop_mug_01", label = "Mug 1" },
            { object = "prop_mug_02", label = "Mug 2" },
            { object = "prop_mug_03", label = "Mug 3" },
            { object = "prop_optic_vodka", label = "Vodka" },
            { object = "prop_optic_jd", label = "JD" },
            { object = "prop_pint_glass_01", label = "Pint Glass" },
            { object = "prop_pizza_box_03", label = "Pizza box" },
            { object = "prop_sandwich_01", label = "Sandwich" },
            { object = "prop_cava", label = "Cava" },
            { object = "prop_drink_redwine", label = "Red wine" },
            { object = "vodkarow", label = "Vodka Row" },
            { object = "prop_cherenkov_02", label = "Cherenkov" },
            { object = "prop_cherenkov_03", label = "Cherenkov 2" },
            { object = "prop_cocktail_glass", label = "Cocktail glass" },
            { object = "prop_cs_bottle_opener", label = "Bottle opener" },
            { object = "prop_food_bs_chips", label = "Chips" },
            { object = "prop_cs_burger_01", label = "Burger" },
            { object = "prop_cs_hand_radio", label = "Hand radio" },
            { object = "prop_cs_hotdog_01", label = "Hotdog" },
            { object = "prop_cs_milk_01", label = "Milk" },
            { object = "prop_cs_panties", label = "Panties" },
            { object = "prop_cs_steak", label = "Meat" },
            { object = "v_ret_csr_bin", label = "CSR Bin" },
            { object = "v_ret_fh_wickbskt", label = "Basket" },
            { object = "v_ret_gc_bag01", label = "GC Bag 1" },
            { object = "v_ret_gc_bag02", label = "GC Bag 2" },
            { object = "v_ret_gc_bin", label = "GC Bin" },
            { object = "v_ret_gc_cashreg", label = "Cash Register" },
            { object = "v_ret_gc_chair01", label = "GC Chair 01" },
            { object = "v_ret_gc_chair02", label = "GC Chair 02" },
            { object = "v_ret_gc_clock", label = "Clock" },
            { object = "v_ret_hd_prod1_", label = "Prod 1" },
            { object = "v_ret_hd_prod2_", label = "Prod 2" },
            { object = "v_ret_hd_prod3_", label = "Prod 3" },
            { object = "v_ret_hd_prod4_", label = "Prod 4" },
            { object = "v_ret_hd_prod5_", label = "Prod 5" },
            { object = "v_ret_hd_prod6_", label = "Prod 6" },
            { object = "v_ret_hd_unit1_", label = "HD Unit 1" },
            { object = "v_ret_hd_unit2_", label = "HD Unit 2" },
            { object = "v_ret_ml_fridge02", label = "Fridge" },
            { object = "v_ret_ps_bag_01", label = "Bag 1" },
            { object = "v_ret_ps_bag_02", label = "Bag 2" },
            { object = "v_ret_ta_book1", label = "Book 1" },
            { object = "v_ret_ta_book2", label = "Book 2" },
            { object = "v_ret_ta_book3", label = "Book 3" },
            { object = "v_ret_ta_book4", label = "Book 4" },
            { object = "v_ret_ta_camera", label = "Cam" },
            { object = "v_ret_ta_firstaid", label = "First Aid" },
            { object = "v_ret_ta_hero", label = "Hero" },
            { object = "v_ret_ta_mag1", label = "Mag 1" },
            { object = "v_ret_ta_mag2", label = "Mag 2" },
            { object = "v_ret_ta_skull", label = "Skull" },
            { object = "prop_acc_guitar_01", label = "Guitar" },
            { object = "prop_amb_handbag_01", label = "Handbag" },
            { object = "prop_attache_case_01", label = "Case" },
            { object = "prop_big_bag_01", label = "Big Bag" },
            { object = "prop_bonesaw", label = "Bonesaw" },
            { object = "prop_cs_fertilizer", label = "Fertilizer" },
            { object = "prop_cs_shopping_bag", label = "Shopping Bag" },
            { object = "prop_cs_vial_01", label = "Vial" },
            { object = "prop_defilied_ragdoll_01", label = "Ragdoll" },
            { object = "v_res_fa_book03", label = "Boek Kamasutra" },
            { object = "prop_weight_rack_02", label = "Dumbbellrek" },
            { object = "prop_weight_bench_02", label = "Couchdrukset" },
            { object = "prop_tool_broom", label = "Broom" },
            { object = "prop_fire_exting_2a", label = "Fire extinguisher" },
            { object = "v_res_vacuum", label = "Vacuum cleaner" },
            { object = "v_ret_gc_fan", label = "Fan" },
            { object = "prop_paint_stepl01b", label = "Ladder" },
            { object = "bkr_prop_weed_bucket_01b", label = "Fertilizer" },
            { object = "v_club_vusnaketank", label = "Terrarium" },
            { object = "prop_pooltable_02", label = "Pool Table" },
            { object = "prop_pool_rack_02", label = "Pool Cues" },
            { object = "v_club_vu_deckcase", label = "DJ Set" },
            { object = "v_corp_servercln", label = "Server Rack" },
            { object = "prop_dummy_01", label = "Dummy" },
            { object = "prop_egg_clock_01", label = "Egg Clock" },
            { object = "prop_el_guitar_01", label = "E Guitar 1" },
            { object = "prop_el_guitar_02", label = "E Guitar 2" },
            { object = "prop_el_guitar_03", label = "E Guitar 3" },
            { object = "prop_feed_sack_01", label = "Feed Sack" },
            { object = "prop_floor_duster_01", label = "Floor Duster" },
            { object = "prop_fruit_basket", label = "Fruit Basket" },
            { object = "prop_f_duster_02", label = "Duster" },
            { object = "prop_grapes_02", label = "Grapes" },
            { object = "prop_hotel_clock_01", label = "Hotel Clock" },
            { object = "prop_idol_case_01", label = "Idol Case" },
            { object = "prop_jewel_02a", label = "Jewels" },
            { object = "prop_jewel_02b", label = "Jewels" },
            { object = "prop_jewel_02c", label = "Jewels" },
            { object = "prop_jewel_03a", label = "Jewels" },
            { object = "prop_jewel_03b", label = "Jewels" },
            { object = "prop_jewel_04a", label = "Jewels" },
            { object = "prop_jewel_04b", label = "Jewels" },
            { object = "prop_j_disptray_01", label = "Display Tray" },
            { object = "prop_j_disptray_01b", label = "Display Tray" },
            { object = "prop_j_disptray_02", label = "Display Tray" },
            { object = "prop_j_disptray_03", label = "Display Tray" },
            { object = "prop_j_disptray_04", label = "Display Tray" },
            { object = "prop_j_disptray_04b", label = "Display Tray" },
            { object = "prop_j_disptray_05", label = "Display Tray" },
            { object = "prop_j_disptray_05b", label = "Display Tray" },
            { object = "prop_ld_greenscreen_01", label = "Green Screen" },
            { object = "prop_ld_handbag", label = "Handbag" },
            { object = "prop_ld_jerrycan_01", label = "Jerry Can" },
            { object = "prop_ld_keypad_01", label = "Keypad 1" },
            { object = "prop_ld_keypad_01b", label = "Keypad 2" },
            { object = "prop_ld_suitcase_01", label = "Suitcase 1" },
            { object = "prop_ld_suitcase_02", label = "Suitcase 2" },
            { object = "hei_p_attache_case_shut", label = "Suitcase 3" },
            { object = "prop_mr_rasberryclean", label = "Rasberry Clean" },
            { object = "prop_paper_bag_01", label = "Paper Bag" },
            { object = "prop_shopping_bags01", label = "Shopping Bags" },
            { object = "prop_shopping_bags02", label = "Shopping Bags 2" },
            { object = "prop_yoga_mat_01", label = "Yoga Mat 1" },
            { object = "prop_yoga_mat_02", label = "Yoga Mat 2" },
            { object = "prop_yoga_mat_03", label = "Yoga Mat 3" },
            { object = "p_ld_sax", label = "Sax" },
            { object = "p_ld_soc_ball_01", label = "SOCCER Ball" },
            { object = "p_watch_01", label = "Watch 1" },
            { object = "p_watch_02", label = "Watch 2" },
            { object = "p_watch_03", label = "Watch 3" },
            { object = "p_watch_04", label = "Watch 4" },
            { object = "p_watch_05", label = "Watch 5" },
            { object = "p_watch_06", label = "Watch 6" },
            { object = "apa_mp_h_acc_candles_01", label = "Candle" },
            { object = "apa_mp_h_acc_candles_02", label = "Candle 2" },
            { object = "apa_mp_h_acc_candles_04", label = "Candle 3" },
            { object = "apa_mp_h_acc_candles_06", label = "Candle 4" },
            { object = "apa_mp_h_acc_fruitbowl_02", label = "Fruit Bowl" },
            { object = "apa_mp_h_acc_tray_01", label = "Thingies" },
            { object = "prop_bskball_01", label = "Basketball" },
            { object = "prop_cs_wrench", label = "Wrench" },
            { object = "prop_cs_bowie_knife", label = "Bowie Knife" },
            { object = "prop_w_me_hatchet", label = "Hatchet" },
        },
    }
}
